/*
 * This file is generated by jOOQ.
*/
package storage.entities.reverse_proxy;


import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;
import storage.entities.DefaultCatalog;
import storage.entities.reverse_proxy.tables.*;

import javax.annotation.Generated;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.10.0"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class ReverseProxy extends SchemaImpl {

    private static final long serialVersionUID = -1647762661;

    /**
     * The reference instance of <code>reverse-proxy</code>
     */
    public static final ReverseProxy REVERSE_PROXY = new ReverseProxy();

    /**
     * The table <code>reverse-proxy.keywords-count-distribution</code>.
     */
    public final KeywordsCountDistribution KEYWORDS_COUNT_DISTRIBUTION = storage.entities.reverse_proxy.tables.KeywordsCountDistribution.KEYWORDS_COUNT_DISTRIBUTION;

    /**
     * The table <code>reverse-proxy.latency-distribution</code>.
     */
    public final LatencyDistribution LATENCY_DISTRIBUTION = storage.entities.reverse_proxy.tables.LatencyDistribution.LATENCY_DISTRIBUTION;

    /**
     * The table <code>reverse-proxy.learn-statistic</code>.
     */
    public final LearnStatistic LEARN_STATISTIC = storage.entities.reverse_proxy.tables.LearnStatistic.LEARN_STATISTIC;

    /**
     * The table <code>reverse-proxy.response-code-distribution</code>.
     */
    public final ResponseCodeDistribution RESPONSE_CODE_DISTRIBUTION = storage.entities.reverse_proxy.tables.ResponseCodeDistribution.RESPONSE_CODE_DISTRIBUTION;

    /**
     * The table <code>reverse-proxy.response-size-distribution</code>.
     */
    public final ResponseSizeDistribution RESPONSE_SIZE_DISTRIBUTION = storage.entities.reverse_proxy.tables.ResponseSizeDistribution.RESPONSE_SIZE_DISTRIBUTION;

    /**
     * No further instances allowed
     */
    private ReverseProxy() {
        super("reverse-proxy", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
                KeywordsCountDistribution.KEYWORDS_COUNT_DISTRIBUTION,
                LatencyDistribution.LATENCY_DISTRIBUTION,
                LearnStatistic.LEARN_STATISTIC,
                ResponseCodeDistribution.RESPONSE_CODE_DISTRIBUTION,
                ResponseSizeDistribution.RESPONSE_SIZE_DISTRIBUTION);
    }
}
