/*
 * This file is generated by jOOQ.
*/
package storage.entities.reverse_proxy;


import storage.entities.reverse_proxy.tables.*;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in reverse-proxy
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.10.0"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Tables {

    /**
     * The table <code>reverse-proxy.keywords-count-distribution</code>.
     */
    public static final KeywordsCountDistribution KEYWORDS_COUNT_DISTRIBUTION = storage.entities.reverse_proxy.tables.KeywordsCountDistribution.KEYWORDS_COUNT_DISTRIBUTION;

    /**
     * The table <code>reverse-proxy.latency-distribution</code>.
     */
    public static final LatencyDistribution LATENCY_DISTRIBUTION = storage.entities.reverse_proxy.tables.LatencyDistribution.LATENCY_DISTRIBUTION;

    /**
     * The table <code>reverse-proxy.learn-statistic</code>.
     */
    public static final LearnStatistic LEARN_STATISTIC = storage.entities.reverse_proxy.tables.LearnStatistic.LEARN_STATISTIC;

    /**
     * The table <code>reverse-proxy.response-code-distribution</code>.
     */
    public static final ResponseCodeDistribution RESPONSE_CODE_DISTRIBUTION = storage.entities.reverse_proxy.tables.ResponseCodeDistribution.RESPONSE_CODE_DISTRIBUTION;

    /**
     * The table <code>reverse-proxy.response-size-distribution</code>.
     */
    public static final ResponseSizeDistribution RESPONSE_SIZE_DISTRIBUTION = storage.entities.reverse_proxy.tables.ResponseSizeDistribution.RESPONSE_SIZE_DISTRIBUTION;
}
