/*
 * This file is generated by jOOQ.
*/
package storage.entities;


import org.jooq.Schema;
import org.jooq.impl.CatalogImpl;
import storage.entities.information_schema.InformationSchema;
import storage.entities.reverse_proxy.ReverseProxy;

import javax.annotation.Generated;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.10.0"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class DefaultCatalog extends CatalogImpl {

    private static final long serialVersionUID = 2027662254;

    /**
     * The reference instance of <code></code>
     */
    public static final DefaultCatalog DEFAULT_CATALOG = new DefaultCatalog();

    /**
     * The schema <code>information_schema</code>.
     */
    public final InformationSchema INFORMATION_SCHEMA = storage.entities.information_schema.InformationSchema.INFORMATION_SCHEMA;

    /**
     * The schema <code>reverse-proxy</code>.
     */
    public final ReverseProxy REVERSE_PROXY = storage.entities.reverse_proxy.ReverseProxy.REVERSE_PROXY;

    /**
     * No further instances allowed
     */
    private DefaultCatalog() {
        super("");
    }

    @Override
    public final List<Schema> getSchemas() {
        List result = new ArrayList();
        result.addAll(getSchemas0());
        return result;
    }

    private final List<Schema> getSchemas0() {
        return Arrays.<Schema>asList(
                InformationSchema.INFORMATION_SCHEMA,
                ReverseProxy.REVERSE_PROXY);
    }
}
