/*
 * This file is generated by jOOQ.
*/
package storage.entities.reverse_proxy.tables;


import org.jooq.*;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;
import storage.entities.reverse_proxy.ReverseProxy;
import storage.entities.reverse_proxy.tables.records.KeywordsCountDistributionRecord;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.10.0"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class KeywordsCountDistribution extends TableImpl<KeywordsCountDistributionRecord> {

    private static final long serialVersionUID = -138749771;

    /**
     * The reference instance of <code>reverse-proxy.keywords-count-distribution</code>
     */
    public static final KeywordsCountDistribution KEYWORDS_COUNT_DISTRIBUTION = new KeywordsCountDistribution();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<KeywordsCountDistributionRecord> getRecordType() {
        return KeywordsCountDistributionRecord.class;
    }

    /**
     * The column <code>reverse-proxy.keywords-count-distribution.request</code>.
     */
    public final TableField<KeywordsCountDistributionRecord, String> REQUEST = createField("request", org.jooq.impl.SQLDataType.VARCHAR(1024).nullable(false), this, "");

    /**
     * The column <code>reverse-proxy.keywords-count-distribution.math_expectation</code>.
     */
    public final TableField<KeywordsCountDistributionRecord, Double> MATH_EXPECTATION = createField("math_expectation", org.jooq.impl.SQLDataType.DOUBLE.nullable(false), this, "");

    /**
     * The column <code>reverse-proxy.keywords-count-distribution.variance</code>.
     */
    public final TableField<KeywordsCountDistributionRecord, Double> VARIANCE = createField("variance", org.jooq.impl.SQLDataType.DOUBLE.nullable(false), this, "");

    /**
     * Create a <code>reverse-proxy.keywords-count-distribution</code> table reference
     */
    public KeywordsCountDistribution() {
        this(DSL.name("keywords-count-distribution"), null);
    }

    /**
     * Create an aliased <code>reverse-proxy.keywords-count-distribution</code> table reference
     */
    public KeywordsCountDistribution(String alias) {
        this(DSL.name(alias), KEYWORDS_COUNT_DISTRIBUTION);
    }

    /**
     * Create an aliased <code>reverse-proxy.keywords-count-distribution</code> table reference
     */
    public KeywordsCountDistribution(Name alias) {
        this(alias, KEYWORDS_COUNT_DISTRIBUTION);
    }

    private KeywordsCountDistribution(Name alias, Table<KeywordsCountDistributionRecord> aliased) {
        this(alias, aliased, null);
    }

    private KeywordsCountDistribution(Name alias, Table<KeywordsCountDistributionRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return ReverseProxy.REVERSE_PROXY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public KeywordsCountDistribution as(String alias) {
        return new KeywordsCountDistribution(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public KeywordsCountDistribution as(Name alias) {
        return new KeywordsCountDistribution(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public KeywordsCountDistribution rename(String name) {
        return new KeywordsCountDistribution(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public KeywordsCountDistribution rename(Name name) {
        return new KeywordsCountDistribution(name, null);
    }
}
