/*
 * This file is generated by jOOQ.
*/
package storage.entities.reverse_proxy.tables;


import org.jooq.*;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;
import storage.entities.reverse_proxy.ReverseProxy;
import storage.entities.reverse_proxy.tables.records.LatencyDistributionRecord;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.10.0"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class LatencyDistribution extends TableImpl<LatencyDistributionRecord> {

    private static final long serialVersionUID = -1874351790;

    /**
     * The reference instance of <code>reverse-proxy.latency-distribution</code>
     */
    public static final LatencyDistribution LATENCY_DISTRIBUTION = new LatencyDistribution();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<LatencyDistributionRecord> getRecordType() {
        return LatencyDistributionRecord.class;
    }

    /**
     * The column <code>reverse-proxy.latency-distribution.request</code>.
     */
    public final TableField<LatencyDistributionRecord, String> REQUEST = createField("request", org.jooq.impl.SQLDataType.VARCHAR(1024).nullable(false), this, "");

    /**
     * The column <code>reverse-proxy.latency-distribution.math_expectation</code>.
     */
    public final TableField<LatencyDistributionRecord, Double> MATH_EXPECTATION = createField("math_expectation", org.jooq.impl.SQLDataType.DOUBLE.nullable(false), this, "");

    /**
     * The column <code>reverse-proxy.latency-distribution.variance</code>.
     */
    public final TableField<LatencyDistributionRecord, Double> VARIANCE = createField("variance", org.jooq.impl.SQLDataType.DOUBLE.nullable(false), this, "");

    /**
     * Create a <code>reverse-proxy.latency-distribution</code> table reference
     */
    public LatencyDistribution() {
        this(DSL.name("latency-distribution"), null);
    }

    /**
     * Create an aliased <code>reverse-proxy.latency-distribution</code> table reference
     */
    public LatencyDistribution(String alias) {
        this(DSL.name(alias), LATENCY_DISTRIBUTION);
    }

    /**
     * Create an aliased <code>reverse-proxy.latency-distribution</code> table reference
     */
    public LatencyDistribution(Name alias) {
        this(alias, LATENCY_DISTRIBUTION);
    }

    private LatencyDistribution(Name alias, Table<LatencyDistributionRecord> aliased) {
        this(alias, aliased, null);
    }

    private LatencyDistribution(Name alias, Table<LatencyDistributionRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return ReverseProxy.REVERSE_PROXY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LatencyDistribution as(String alias) {
        return new LatencyDistribution(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LatencyDistribution as(Name alias) {
        return new LatencyDistribution(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public LatencyDistribution rename(String name) {
        return new LatencyDistribution(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public LatencyDistribution rename(Name name) {
        return new LatencyDistribution(name, null);
    }
}
