/*
 * This file is generated by jOOQ.
*/
package storage.entities.reverse_proxy.tables;


import org.jooq.*;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;
import storage.entities.reverse_proxy.ReverseProxy;
import storage.entities.reverse_proxy.tables.records.LearnStatisticRecord;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.10.0"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class LearnStatistic extends TableImpl<LearnStatisticRecord> {

    private static final long serialVersionUID = 1857942061;

    /**
     * The reference instance of <code>reverse-proxy.learn-statistic</code>
     */
    public static final LearnStatistic LEARN_STATISTIC = new LearnStatistic();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<LearnStatisticRecord> getRecordType() {
        return LearnStatisticRecord.class;
    }

    /**
     * The column <code>reverse-proxy.learn-statistic.request</code>.
     */
    public final TableField<LearnStatisticRecord, String> REQUEST = createField("request", org.jooq.impl.SQLDataType.VARCHAR(1024).nullable(false), this, "");

    /**
     * The column <code>reverse-proxy.learn-statistic.code</code>.
     */
    public final TableField<LearnStatisticRecord, Integer> CODE = createField("code", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>reverse-proxy.learn-statistic.size</code>.
     */
    public final TableField<LearnStatisticRecord, Integer> SIZE = createField("size", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>reverse-proxy.learn-statistic.html_tags_count</code>.
     */
    public final TableField<LearnStatisticRecord, Integer> HTML_TAGS_COUNT = createField("html_tags_count", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>reverse-proxy.learn-statistic.latency</code>.
     */
    public final TableField<LearnStatisticRecord, Integer> LATENCY = createField("latency", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * Create a <code>reverse-proxy.learn-statistic</code> table reference
     */
    public LearnStatistic() {
        this(DSL.name("learn-statistic"), null);
    }

    /**
     * Create an aliased <code>reverse-proxy.learn-statistic</code> table reference
     */
    public LearnStatistic(String alias) {
        this(DSL.name(alias), LEARN_STATISTIC);
    }

    /**
     * Create an aliased <code>reverse-proxy.learn-statistic</code> table reference
     */
    public LearnStatistic(Name alias) {
        this(alias, LEARN_STATISTIC);
    }

    private LearnStatistic(Name alias, Table<LearnStatisticRecord> aliased) {
        this(alias, aliased, null);
    }

    private LearnStatistic(Name alias, Table<LearnStatisticRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return ReverseProxy.REVERSE_PROXY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LearnStatistic as(String alias) {
        return new LearnStatistic(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LearnStatistic as(Name alias) {
        return new LearnStatistic(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public LearnStatistic rename(String name) {
        return new LearnStatistic(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public LearnStatistic rename(Name name) {
        return new LearnStatistic(name, null);
    }
}
