/*
 * This file is generated by jOOQ.
*/
package storage.entities.reverse_proxy.tables;


import org.jooq.*;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;
import storage.entities.reverse_proxy.ReverseProxy;
import storage.entities.reverse_proxy.tables.records.ResponseSizeDistributionRecord;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.10.0"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class ResponseSizeDistribution extends TableImpl<ResponseSizeDistributionRecord> {

    private static final long serialVersionUID = 890590477;

    /**
     * The reference instance of <code>reverse-proxy.response-size-distribution</code>
     */
    public static final ResponseSizeDistribution RESPONSE_SIZE_DISTRIBUTION = new ResponseSizeDistribution();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ResponseSizeDistributionRecord> getRecordType() {
        return ResponseSizeDistributionRecord.class;
    }

    /**
     * The column <code>reverse-proxy.response-size-distribution.request</code>.
     */
    public final TableField<ResponseSizeDistributionRecord, String> REQUEST = createField("request", org.jooq.impl.SQLDataType.VARCHAR(1024).nullable(false), this, "");

    /**
     * The column <code>reverse-proxy.response-size-distribution.math_expectation</code>.
     */
    public final TableField<ResponseSizeDistributionRecord, Double> MATH_EXPECTATION = createField("math_expectation", org.jooq.impl.SQLDataType.DOUBLE.nullable(false), this, "");

    /**
     * The column <code>reverse-proxy.response-size-distribution.variance</code>.
     */
    public final TableField<ResponseSizeDistributionRecord, Double> VARIANCE = createField("variance", org.jooq.impl.SQLDataType.DOUBLE.nullable(false), this, "");

    /**
     * Create a <code>reverse-proxy.response-size-distribution</code> table reference
     */
    public ResponseSizeDistribution() {
        this(DSL.name("response-size-distribution"), null);
    }

    /**
     * Create an aliased <code>reverse-proxy.response-size-distribution</code> table reference
     */
    public ResponseSizeDistribution(String alias) {
        this(DSL.name(alias), RESPONSE_SIZE_DISTRIBUTION);
    }

    /**
     * Create an aliased <code>reverse-proxy.response-size-distribution</code> table reference
     */
    public ResponseSizeDistribution(Name alias) {
        this(alias, RESPONSE_SIZE_DISTRIBUTION);
    }

    private ResponseSizeDistribution(Name alias, Table<ResponseSizeDistributionRecord> aliased) {
        this(alias, aliased, null);
    }

    private ResponseSizeDistribution(Name alias, Table<ResponseSizeDistributionRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return ReverseProxy.REVERSE_PROXY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ResponseSizeDistribution as(String alias) {
        return new ResponseSizeDistribution(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ResponseSizeDistribution as(Name alias) {
        return new ResponseSizeDistribution(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public ResponseSizeDistribution rename(String name) {
        return new ResponseSizeDistribution(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ResponseSizeDistribution rename(Name name) {
        return new ResponseSizeDistribution(name, null);
    }
}
