/*
 * This file is generated by jOOQ.
*/
package storage.entities.reverse_proxy.tables.records;


import org.jooq.Field;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.TableRecordImpl;
import storage.entities.reverse_proxy.tables.LatencyDistribution;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.10.0"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class LatencyDistributionRecord extends TableRecordImpl<LatencyDistributionRecord> implements Record3<String, Double, Double> {

    private static final long serialVersionUID = -1268848109;

    /**
     * Setter for <code>reverse-proxy.latency-distribution.request</code>.
     */
    public void setRequest(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>reverse-proxy.latency-distribution.request</code>.
     */
    public String getRequest() {
        return (String) get(0);
    }

    /**
     * Setter for <code>reverse-proxy.latency-distribution.math_expectation</code>.
     */
    public void setMathExpectation(Double value) {
        set(1, value);
    }

    /**
     * Getter for <code>reverse-proxy.latency-distribution.math_expectation</code>.
     */
    public Double getMathExpectation() {
        return (Double) get(1);
    }

    /**
     * Setter for <code>reverse-proxy.latency-distribution.variance</code>.
     */
    public void setVariance(Double value) {
        set(2, value);
    }

    /**
     * Getter for <code>reverse-proxy.latency-distribution.variance</code>.
     */
    public Double getVariance() {
        return (Double) get(2);
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<String, Double, Double> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<String, Double, Double> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return LatencyDistribution.LATENCY_DISTRIBUTION.REQUEST;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field2() {
        return LatencyDistribution.LATENCY_DISTRIBUTION.MATH_EXPECTATION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field3() {
        return LatencyDistribution.LATENCY_DISTRIBUTION.VARIANCE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getRequest();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double component2() {
        return getMathExpectation();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double component3() {
        return getVariance();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getRequest();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value2() {
        return getMathExpectation();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value3() {
        return getVariance();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LatencyDistributionRecord value1(String value) {
        setRequest(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LatencyDistributionRecord value2(Double value) {
        setMathExpectation(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LatencyDistributionRecord value3(Double value) {
        setVariance(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LatencyDistributionRecord values(String value1, Double value2, Double value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached LatencyDistributionRecord
     */
    public LatencyDistributionRecord() {
        super(LatencyDistribution.LATENCY_DISTRIBUTION);
    }

    /**
     * Create a detached, initialised LatencyDistributionRecord
     */
    public LatencyDistributionRecord(String request, Double mathExpectation, Double variance) {
        super(LatencyDistribution.LATENCY_DISTRIBUTION);

        set(0, request);
        set(1, mathExpectation);
        set(2, variance);
    }
}
