/*
 * This file is generated by jOOQ.
*/
package storage.entities.reverse_proxy.tables.records;


import org.jooq.Field;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.TableRecordImpl;
import storage.entities.reverse_proxy.tables.ResponseCodeDistribution;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.10.0"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class ResponseCodeDistributionRecord extends TableRecordImpl<ResponseCodeDistributionRecord> implements Record3<String, Integer, Double> {

    private static final long serialVersionUID = -101008955;

    /**
     * Setter for <code>reverse-proxy.response-code-distribution.request</code>.
     */
    public void setRequest(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>reverse-proxy.response-code-distribution.request</code>.
     */
    public String getRequest() {
        return (String) get(0);
    }

    /**
     * Setter for <code>reverse-proxy.response-code-distribution.value</code>.
     */
    public void setValue(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>reverse-proxy.response-code-distribution.value</code>.
     */
    public Integer getValue() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>reverse-proxy.response-code-distribution.probability</code>.
     */
    public void setProbability(Double value) {
        set(2, value);
    }

    /**
     * Getter for <code>reverse-proxy.response-code-distribution.probability</code>.
     */
    public Double getProbability() {
        return (Double) get(2);
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<String, Integer, Double> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<String, Integer, Double> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return ResponseCodeDistribution.RESPONSE_CODE_DISTRIBUTION.REQUEST;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return ResponseCodeDistribution.RESPONSE_CODE_DISTRIBUTION.VALUE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field3() {
        return ResponseCodeDistribution.RESPONSE_CODE_DISTRIBUTION.PROBABILITY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getRequest();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getValue();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double component3() {
        return getProbability();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getRequest();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getValue();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value3() {
        return getProbability();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ResponseCodeDistributionRecord value1(String value) {
        setRequest(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ResponseCodeDistributionRecord value2(Integer value) {
        setValue(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ResponseCodeDistributionRecord value3(Double value) {
        setProbability(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ResponseCodeDistributionRecord values(String value1, Integer value2, Double value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ResponseCodeDistributionRecord
     */
    public ResponseCodeDistributionRecord() {
        super(ResponseCodeDistribution.RESPONSE_CODE_DISTRIBUTION);
    }

    /**
     * Create a detached, initialised ResponseCodeDistributionRecord
     */
    public ResponseCodeDistributionRecord(String request, Integer value, Double probability) {
        super(ResponseCodeDistribution.RESPONSE_CODE_DISTRIBUTION);

        set(0, request);
        set(1, value);
        set(2, probability);
    }
}
